services:
  tests:
    build: .
    container_name: tests-server
    depends_on:
      api-mock:
        condition: service_started
    environment:
      - REQUESTS_CA_BUNDLE=/root/ca/rsa/volumed_dir/full-chain.cert.pem
    working_dir: /opt/project/tests
    volumes:
      - ./tests:/opt/project/tests
      - api_mock_certs:/root/ca/rsa/volumed_dir
    entrypoint: ["sh", "-c", "pytest -v /opt/project/tests"]
  
  api-mock:
    build: .
    container_name: api-mock-server
    restart: always
    volumes:
      - api_mock_certs:/root/ca/rsa/volumed_dir
    ports:
      - "8080:80"
      - "8443:443"

  mock-database:
    image: postgres:latest
    container_name: mock-db-server
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mockdb
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
# Uncomment the line below if you want an empty database setup
#      - ./database/empty.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

volumes:
  api_mock_certs: {}