services:
  tests:
    # TODO by students: create own tests image using separate Dockerfile
    build: .
    container_name: tests-server
    depends_on:
      api-mock:
        condition: service_started
    environment:
      - REQUESTS_CA_BUNDLE=/root/ca/rsa/volumed_dir/full-chain.cert.pem
    working_dir: /opt/project
    volumes:
      - .:/opt/project
      - api_mock_certs:/root/ca/rsa/volumed_dir
    # entrypoint: ["sh", "-c", "while true; do sleep 1000; done"] infinite loop to run container
    entrypoint: ["ping", "-c", "5", "api-mock-server"]

  api-mock:
    build: .
    container_name: api-mock-server
    volumes:
      - api_mock_certs:/root/ca/rsa/volumed_dir
    expose:
      - "80"
      - "443"

volumes:
  api_mock_certs:
