FROM python:3.11-slim
USER root

# Set the working directory inside the container
WORKDIR /opt/project

# Copy a list of required packages into the container
COPY python_packages.txt /opt/project/python_packages.txt
RUN pip install --no-cache-dir -r python_packages.txt

CMD [ "pytest" ]