FROM python:3.11
USER root

# Set the working directory inside the container
WORKDIR /opt/project

# Copy debian packages file and install required packages
RUN apt-get update && \
    apt-get install -y ca-certificates && \
    pip install --upgrade certifi && \
    rm -rf /var/lib/apt/lists/*

# Create a virtual environment and install pytest
RUN python3 -m venv /opt/project/venv && \
    /opt/project/venv/bin/pip install --upgrade pip setuptools && \
    /opt/project/venv/bin/pip install pytest && \
    /opt/project/venv/bin/pip install requests && \
    /opt/project/venv/bin/pip list

# Copy the project files into the container
COPY . /opt/project/

# Set environment variables
ENV REQUESTS_CA_BUNDLE=/root/ca/rsa/volumed_dir/full-chain.cert.pem
ENV PYTHONWARNINGS="ignore:Unverified HTTPS request"
ENV PYTHONPATH=/opt/project

# Set the path to use the virtual environment
ENV PATH="/opt/project/venv/bin:$PATH"